name: push when publishing from draft

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "draft_entries/**"

jobs:
  push-when-publishing-from-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-when-publishing-from-draft.yaml@1fc8993fdb5727ca6172542e038e9c28d0d2bef0 # v2.0.13
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
