name: push published entries


on:
  pull_request:
    paths:
      - "entries/**"

jobs:
  push-published-entries:
    uses: hatena/hatenablog-workflows/.github/workflows/push-published-entries.yaml@1fc8993fdb5727ca6172542e038e9c28d0d2bef0 # v2.0.13
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
